INSERT INTO tasks (label, description, completed) VALUES
('Acheter du café', 'Aller au supermarché pour acheter du café', FALSE),
('Rédiger le rapport', 'Préparer le rapport mensuel', TRUE),
('Appeler le client', 'Faire un point avec le client sur le projet', FALSE),
('Organiser réunion équipe', 'Planifier la réunion hebdomadaire', TRUE),
('Mettre à jour le site web', 'Ajouter les nouvelles pages produits', FALSE),
('Envoyer newsletter', 'Envoyer la newsletter mensuelle', TRUE),
('Faire sauvegarde serveur', 'Vérifier les backups du serveur', FALSE),
('Réviser budget', 'Analyser le budget du mois', TRUE),
('Commander fournitures', 'Commander stylos et papier', FALSE),
('Planifier formation', 'Organiser la formation interne', TRUE),
('Nettoyer bureau', 'Ranger et nettoyer le bureau', FALSE),
('Préparer présentation', 'Créer diaporama pour réunion', TRUE),
('Répondre emails clients', 'Traiter les emails en attente', FALSE),
('Mettre à jour CRM', 'Entrer les nouvelles informations clients', TRUE),
('Vérifier factures', 'Contrôler les factures fournisseurs', FALSE),
('Faire inventaire', 'Lister le matériel en stock', TRUE),
('Appeler fournisseur', 'Confirmer livraison prochaine', FALSE),
('Créer rapport ventes', 'Préparer rapport hebdomadaire', TRUE),
('Tester application', 'Vérifier les fonctionnalités', FALSE),
('Mettre à jour base données', 'Synchroniser données récentes', TRUE),
('Envoyer devis', 'Envoyer devis aux clients', FALSE),
('Réserver salle réunion', 'Réserver salle pour conférence', TRUE),
('Analyser concurrence', 'Étudier les concurrents directs', FALSE),
('Écrire article blog', 'Publier article SEO', TRUE),
('Organiser team building', 'Planifier activité équipe', FALSE),
('Mettre à jour réseaux sociaux', 'Publier posts Instagram/Facebook', TRUE),
('Vérifier tickets support', 'Traiter tickets en attente', FALSE),
('Préparer facture client', 'Émettre facture pour prestation', TRUE),
('Réviser procédure', 'Mettre à jour la procédure interne', FALSE),
('Planifier audit interne', 'Organiser audit département', TRUE),
('Envoyer invitation', 'Envoyer invitation événement', FALSE),
('Faire reporting mensuel', 'Préparer reporting financier', TRUE),
('Créer campagne marketing', 'Lancer campagne promotionnelle', FALSE),
('Analyser feedback clients', 'Étudier retours clients', TRUE),
('Mise à jour logiciel', 'Installer dernière version', FALSE),
('Préparer contrat', 'Rédiger contrat nouveau client', TRUE),
('Suivre livraison', 'Vérifier suivi colis fournisseur', FALSE),
('Former stagiaire', 'Expliquer procédure interne', TRUE),
('Vérifier stocks', 'Contrôler stocks magasin', FALSE),
('Mettre en place KPI', 'Définir indicateurs performance', TRUE),
('Appeler prospect', 'Contacter nouveau prospect', FALSE),
('Organiser réunion projet', 'Coordonner équipe projet', TRUE),
('Mettre à jour planning', 'Actualiser planning équipe', FALSE),
('Écrire compte rendu', 'Rédiger compte rendu réunion', TRUE),
('Envoyer rapport RH', 'Transmettre rapport au service RH', FALSE),
('Réparer imprimante', 'Diagnostiquer et réparer imprimante', TRUE),
('Mettre à jour politique interne', 'Réviser règlement interne', FALSE),
('Préparer présentation client', 'Créer support pour client', TRUE),
('Analyser ventes produits', 'Étudier ventes du mois', FALSE),
('Planifier maintenance', 'Préparer maintenance serveur', TRUE),
('Répondre appels', 'Gérer appels entrants', FALSE);
